### ISSUE TITLE
email Validation missing

### ISSUE THREAD

**Issue by sunny2319** [debasistripathy01/DreamStore#66]
https://github.com/debasistripathy01/plausible-porter-6646/blob/bbebe5f7096a036ce6d8d631155bce8c516083cd/src/Components/LoginAuth/Signup.jsx#L25

**Comment by debasistripathy01** [comment]
Yes thanks for feedback. Currently working on it. Thanks

**Comment by debasistripathy01** [comment]
I will update in this thread once its done.

**Comment by deep1296** [comment]
Done the task
