### ISSUE TITLE
both email are not matched

### ISSUE THREAD

**Issue by sunny2319** [debasistripathy01/DreamStore#67]
https://github.com/debasistripathy01/plausible-porter-6646/blob/bbebe5f7096a036ce6d8d631155bce8c516083cd/src/Components/LoginAuth/Signup.jsx#L64

**Comment by debasistripathy01** [comment]
- [ ] Yes Currently Working on it,
- [ ] Going to introduce everything 
- [ ] Taking a bit time on some other important issues

**Comment by deep1296** [comment]
Done the task
